openapi: 3.0.0
info:
  version: 1.0.0
  title: Example API
  description: This is an example OpenAPI 3.0 YAML template
paths:
  /example:
    get:
      summary: Get example resource
      responses:
        '200':
          description: Successful operation
    post:
      summary: Create example resource files
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Resource created